name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - main  # Trigger deployment when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: '389.0.0'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  

    - name: Deploy to Google App Engine
      run: |
        gcloud config set project white-berm-449809-n8
        gcloud app deploy --quiet