# Generated by Django 5.1 on 2024-09-13 12:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0016_alter_survey_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='success_page_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Success Page Content'),
        ),
    ]
